const employees = [
{
    id: 1,
    fio: "Помидоркина Анжела Витальевна",
    birthday: "24.04.2004",
    gender: "Ж"
},
{
    id: 2,
    fio: "Тушканчиков Дмитрий Викторович",
    birthday: "23.09.1998",
    gender: "м"
},
{
    id: 3,
    fio: "Баклажанов Борис Эдуардович",
    birthday: "24.09.1987",
    gender: "м"
},
{ 
    id: 4,
    fio: "Лимонов Леонид Львов",
    birthday: "11.11.1991",
    gender: "м"
}
]
console.log(employees[1].id + " - " + employees[1].fio + " - " + employees[1].birthday + " - " + employees[1].gender)