const employees = {
    id: 1,
    fio: "Помидоркина Анжела Витальевна",
    birthday: "24.04.2004",
    gender: "Ж",

    id: 2,
    fio: "Тушканчиков Дмитрий Викторович",
    birthday: "23.09.1998",
    gender: "м",
};
const clients = {
    id: 3,
    fio: "Баклажанов Борис Каримович",
    birthday: "28.10.1908",
    gender: "м",

    id: 4,
    fio: "Криволинейная Карина Эдуардовна",
    birthday: "11.01.2000",
    gender: "Ж",
};
const contacts = {
    id: 5,
    fio: "Тушканчиков Дмитрий Викторвич",
    phone: "+79826718373",
    e_mail: "Tushkanchik21yo@mail.ru",

    id: 6,
    fio: "Баклажанов Борис Каримович",
    phone: "+79123456178",
    e_mail: "BorisBaclazhan@mail.ru",
};

console.log(employees.id + " - " + employees.fio + " - " + employees.birthday + " - " + employees.gender + " - " + clients.id + " - " + clients.fio + " - " + clients.birthday + " - " + clients.gender);
